- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- readme.md
This PR includes new files:
* CODE_OF_CONDUCT.md
*  CONTRIBUTING.md 
And refactoring the readme file.
> Improve the Readme and contribuiting files

- content/en/categories/languages-frameworks/docker.md
Signed-off-by: Otavio Santana <otaviopolianasantana@gmail.com>
> Fix docker marsher

- content/en/categories/languages-frameworks/docker.md
- content/en/categories/languages-frameworks/enry.md
- content/en/categories/languages-frameworks/go.md
- content/en/categories/languages-frameworks/gorm.md
- content/en/categories/languages-frameworks/grpc.md
- content/en/categories/languages-frameworks/horusec.md
- content/en/categories/languages-frameworks/javascript.md
- content/en/categories/languages-frameworks/kubernetes.md
- content/en/categories/languages-frameworks/react.md
- content/en/categories/languages-frameworks/typescript.md
- content/en/categories/platforms/artifact.md
- content/en/categories/platforms/aws.md
- content/en/categories/platforms/dockerhub.md
- content/en/categories/platforms/github.md
- content/en/categories/platforms/shortcut.md
- content/en/categories/techniques/_index.md
- content/en/categories/techniques/cd.md
- content/en/categories/techniques/ic.md
- content/en/categories/techniques/microfrontend.md
- content/en/categories/techniques/microservices.md
- content/en/categories/techniques/monorepo.md
- content/en/categories/techniques/visitor.md
- content/en/categories/tools/git.md
- content/en/categories/tools/helm.md
Signed-off-by: TapiaGus <gustavo.tapia@zup.com.br>
What did I do?
- Translated the Categories section to English
- Translated categories/languages-frameworks to English
- Translated categories/platforms to English
- Translated categories/techniques to English
- Translated categories/tools to English
> translated categories section

- CONTRIBUTING.md
- content/en/categories/languages-frameworks/docker.md
- content/en/categories/languages-frameworks/enry.md
- content/en/categories/languages-frameworks/go.md
- content/en/categories/languages-frameworks/gorm.md
- content/en/categories/languages-frameworks/grpc.md
- content/en/categories/languages-frameworks/horusec.md
- content/en/categories/languages-frameworks/javascript.md
- content/en/categories/languages-frameworks/kubernetes.md
- content/en/categories/languages-frameworks/react.md
- content/en/categories/languages-frameworks/typescript.md
- content/en/categories/platforms/artifact.md
- content/en/categories/platforms/aws.md
- content/en/categories/platforms/dockerhub.md
- content/en/categories/platforms/github.md
- content/en/categories/platforms/shortcut.md
- content/en/categories/techniques/cd.md
- content/en/categories/techniques/ic.md
- content/en/categories/techniques/microfrontend.md
- content/en/categories/techniques/microservices.md
- content/en/categories/techniques/monorepo.md
- content/en/categories/techniques/visitor.md
- content/en/categories/tools/git.md
- content/en/categories/tools/helm.md
- content/en/docs/_index.md
- content/en/radar/_index.md
- content/en/rings/_index.md
- content/en/rings/potential.md
- content/en/rings/strategic.md
- readme.md
Signed-off-by: jessica-tw <jessica.olinda@zup.com.br>
- Reviewed the whole English section.
- Reviewed and updated README and Contributing Guide.
> Doc Review: English section

- readme.md
Signed-off-by: jessica-tw <jessica.olinda@zup.com.br>
- Fixed readme file.
> Fix read me

- content/en/categories/languages-frameworks/docker.md
- content/en/categories/languages-frameworks/enry.md
- content/en/categories/languages-frameworks/go.md
- content/en/categories/languages-frameworks/gorm.md
- content/en/categories/languages-frameworks/grpc.md
- content/en/categories/languages-frameworks/horusec.md
- content/en/categories/languages-frameworks/javascript.md
- content/en/categories/languages-frameworks/kubernetes.md
- content/en/categories/languages-frameworks/react.md
- content/en/categories/languages-frameworks/typescript.md
Signed-off-by: darwinaraujozup <darwin.araujo@zup.com.br>
> fix: remove a quadrant from english version

- themes/techradar/static/js/components/dropdown.js
Signed-off-by: darwinaraujozup <darwin.araujo@zup.com.br>
> fix: language change

- .github/workflows/publish-prod.yml
Updates permanent keys for AWS bucket
Signed-off-by: Hector Custódio <hector.custodio@zup.com.br>
> feat: Updates AWS keys

- config.toml
> chore: update baseURL

- themes/techradar/layouts/_default/radar.html
- "?" displays description on mouse over
> Add tooltip with description category

- themes/techradar/static/js/components/accordion.js
- By clicking on the menu scroll to the top of the category
> Hotfix Accorddion scroll

- themes/techradar/static/js/app.js
- a validation has been added to not pick up empty objects
- added "alt" to thumbnail image
> add object empty validation and add alt into thumbnail

- themes/techradar/assets/js/offline-search.js
> fix: search results

- content/en/categories/techniques/cd.md
- themes/lucas/layouts/_default/details.html
- themes/lucas/layouts/partials/categories.html
- themes/lucas/layouts/partials/header.html
- themes/lucas/layouts/shortcodes/tech-accordion.html
- themes/techradar/layouts/_default/categories.html
- themes/techradar/layouts/_default/details.html
- themes/techradar/layouts/_default/docs.html
- themes/techradar/layouts/index.html
- themes/techradar/layouts/shortcodes/tech-accordion.html
> fix: fix errors

- static/images/icons/close2.svg
- themes/techradar/layouts/_default/radar.html
- themes/techradar/static/css/pages/radar.css
- themes/techradar/static/js/app.js
> feat: add close button to radar modal

- content/en/categories/languages-frameworks/docker.md
- content/en/categories/languages-frameworks/enry.md
- content/en/categories/languages-frameworks/gorm.md
- content/en/categories/languages-frameworks/kubernetes.md
- content/en/categories/platforms/artifact.md
- content/en/categories/platforms/aws.md
- content/en/categories/techniques/cd.md
- content/en/categories/techniques/ic.md
- content/en/categories/techniques/microfrontend.md
- content/en/categories/techniques/microservices.md
- content/en/categories/techniques/monorepo.md
- content/en/categories/techniques/visitor.md
- content/pt-br/categories/languages-frameworks/gorm.md
> fix: all imagens from english version

- themes/techradar/layouts/_default/categories.html
- themes/techradar/layouts/_default/category.html
- themes/techradar/layouts/_default/details.html
- themes/techradar/layouts/_default/docs.html
- themes/techradar/layouts/_default/radar.html
- themes/techradar/layouts/partials/footer.html
- themes/techradar/layouts/partials/head.html
- themes/techradar/layouts/partials/header.html
- themes/techradar/layouts/partials/navbar-lang-selector.html
- themes/techradar/layouts/partials/scripts.html
- themes/techradar/layouts/shortcodes/tech-accordion.html
> chore: update build on actions

- package.json
- themes/techradar/layouts/index.html
- themes/techradar/layouts/page-about.html
- themes/techradar/layouts/page-radar.html
- themes/techradar/layouts/page-technologies.html
- themes/techradar/layouts/partials/scripts.html
- themes/techradar/layouts/partials/search.html
- themes/techradar/layouts/single-technologies.html
> change base url

- config.toml
> chore: update config file

- config.toml
- content/pt-br/radar/_index.md
- themes/techradar/layouts/_default/single.json.json
- themes/techradar/layouts/partials/navbar.html
> chore: update menu configs
